In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [8]:
X = dataset.iloc[:,3:13].values
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [9]:
y = dataset.iloc[:,13].values
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [10]:
# Encoding categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
X

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [11]:
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [12]:
#creating dummy_variables
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()

C:\Users\vu995fy\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\vu995fy\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [13]:
X

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [14]:
X = X[:, 1:]

In [15]:
from sklearn.model_selection import train_test_split
#from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [16]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [42]:
X_test

array([[ 1.75486502, -0.57369368, -0.55204276, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [-0.5698444 , -0.57369368, -1.31490297, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-0.5698444 ,  1.74309049,  0.57162971, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-0.5698444 ,  1.74309049, -0.74791227, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [ 1.75486502, -0.57369368, -0.00566991, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [ 1.75486502, -0.57369368, -0.79945688, ...,  0.64259497,
        -1.03227043,  1.61255917]])

In [31]:
import keras
#initializes neural networks
from tensorflow.keras.models import Sequential
#creates layers in artificial neural networks
from keras.layers import Dense
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten

In [32]:
from keras.layers import Dropout

In [33]:
#initializing the ANN
classifier = Sequential()

In [34]:
#randomly initialize the weights to small numbers close to zero
#input the first observation of your dataset in the input layer, each feature in one input node
#forward propagation - left to right - the neurons are activated in a way taht the impact of each neuron's activation is limited by weights. Propagate the activations until getting the predicted result y
#compare the predicted result to the actual result, measure the generated error
#back propagation- right to left - error is back propagated,update the weights according to how much they are responsible for the error,the learnig rate decides how much do we update the weights
#repeat steps 1 to 5
#when the whole training set is passed through the ANN, that makes the epoch. Do more epochs

In [36]:
classifier.add(Dense(6,kernel_initializer='uniform', input_dim=11))
classifier.add(Dropout(p = 0.1))

Instructions for updating:
Colocations handled automatically by placer.


C:\Users\vu995fy\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  


In [37]:
classifier.add(Activation('relu'))

In [38]:
#adding the second hidden layer
classifier.add(Dense(6,kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dropout(p = 0.1))

C:\Users\vu995fy\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  This is separate from the ipykernel package so we can avoid doing imports until


In [39]:
#output layer
#replacing with sigmoid activation function to have the probability at the ouput layer
classifier.add(Dense(1,kernel_initializer = 'uniform', activation = 'sigmoid'))

In [40]:
#compiling the ANN
#binary outcome so loss function, accuracy to improve the model performance
classifier.compile(optimizer ='adam', loss ='binary_crossentropy', metrics = ['accuracy'])

In [41]:
classifier.fit(X_train, y_train, batch_size =10, nb_epoch=100)

Instructions for updating:
Use tf.cast instead.


C:\Users\vu995fy\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/100
8000/8000 [==============================] - 1s 127us/step - loss: 0.4895 - accuracy: 0.7959
Epoch 2/100
8000/8000 [==============================] - 1s 99us/step - loss: 0.4378 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.4351 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 97us/step - loss: 0.4306 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 93us/step - loss: 0.4310 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 97us/step - loss: 0.4307 - accuracy: 0.7960
Epoch 7/100
8000/8000 [==============================] - 1s 108us/step - loss: 0.4278 - accuracy: 0.8066
Epoch 8/100
8000/8000 [==============================] - 1s 114us/step - loss: 0.4247 - accuracy: 0.8248
Epoch 9/100
8000/8000 [==============================] - 1s 100us/step - loss: 0.4252 - accuracy: 0.8276
Epoch 10/100
8000/8000 [==============================] - 1

8000/8000 [==============================] - 1s 121us/step - loss: 0.4218 - accuracy: 0.8300
Epoch 79/100
8000/8000 [==============================] - 1s 133us/step - loss: 0.4223 - accuracy: 0.8307
Epoch 80/100
8000/8000 [==============================] - 2s 212us/step - loss: 0.4191 - accuracy: 0.8319
Epoch 81/100
8000/8000 [==============================] - 1s 180us/step - loss: 0.4221 - accuracy: 0.8307
Epoch 82/100
8000/8000 [==============================] - 1s 166us/step - loss: 0.4202 - accuracy: 0.8298
Epoch 83/100
8000/8000 [==============================] - ETA: 0s - loss: 0.4214 - accuracy: 0.83 - 1s 139us/step - loss: 0.4195 - accuracy: 0.8316
Epoch 84/100
8000/8000 [==============================] - 1s 147us/step - loss: 0.4198 - accuracy: 0.8340
Epoch 85/100
8000/8000 [==============================] - 1s 126us/step - loss: 0.4186 - accuracy: 0.8303
Epoch 86/100
8000/8000 [==============================] - 1s 124us/step - loss: 0.4217 - accuracy: 0.8330
Epoch 87/100
8000

In [31]:
y_pred = classifier.predict(X_test)

In [32]:
#probabolities of the customers leaving the bank, 1st one has 25% chance to leace the bank
y_pred

array([[0.17687324],
       [0.33393317],
       [0.15793908],
       ...,
       [0.15357381],
       [0.13934475],
       [0.09980634]], dtype=float32)

In [33]:
#less than 50% not leaving the bank
y_pred = (y_pred>0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [1]:
import keras
#initializes neural networks
from tensorflow.keras.models import Sequential
#creates layers in artificial neural networks
from keras.layers import Dense
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten

Using TensorFlow backend.


In [2]:
#Evaluating and improving the ANN, k fold cross validation
import keras
from keras.wrappers.scikit_learn import KerasClassifier

In [19]:
#check if the accuracy is closer to what we obtained earlier
#check for low bias and low variance, high accuracies and low differences between them
from sklearn.model_selection import cross_val_score
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(6,kernel_initializer='uniform', activation = 'relu', input_dim=11))
    #classifier.add(Activation('relu'))
    classifier.add(Dense(output_dim = 6,kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(output_dim = 1,kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer ='adam', loss ='binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier,batch_size = 10, nb_epoch = 100)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1 )
    
                   
    

In [20]:
accuracies

array([0.78625   , 0.79000002, 0.80000001, 0.78250003, 0.81625003,
       0.82499999, 0.78750002, 0.79374999, 0.79874998, 0.79500002])

In [24]:
mean = accuracies.mean()
variance = accuracies.std()


0.012820876732694551

In [26]:
mean



0.7975000083446503

In [27]:
variance

0.012820876732694551

In [43]:
#improving ANN
#dropout regularization to reduce overfitting if needed - drop out works this way - at each iteration of the training neurons of
#your ANN is randomly disabled to prevent them from being too dependant on each other when they learn the correlations,and therefore
#by overiding the neurons, the ANN discovers several independant correlations in the data because each time there is not the
#same configurations of the neurons. This prevents the neurons from learning too much, hence preventing over fitting
from keras.layers import Dropout


In [44]:
#parameter tuning with gridsearch
import keras
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(6,kernel_initializer='uniform', activation = 'relu', input_dim=11))
    #classifier.add(Activation('relu'))
    classifier.add(Dense(output_dim = 6,kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(output_dim = 1,kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer =optimizer, loss ='binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier)


In [45]:
#dictionary,hyperparameter and values
parameters = {'batch_size': [25,32],
             'nb_epoch':[100,500],
             'optimizer':['adam','rmsprop']}

In [46]:
#k-fold cross validation is going to be used to evaluate the accuracy
grid_search = GridSearchCV(estimator = classifier, param_grid = parameters, scoring = 'accuracy', cv=10 )

In [47]:
grid_search.fit(X_train, y_train)

C:\Users\vu995fy\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="relu", units=6)`
  if __name__ == '__main__':
C:\Users\vu995fy\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", activation="sigmoid", units=1)`
  # Remove the CWD from sys.path while we load stuff.


Epoch 1/1
7200/7200 [==============================] - 0s 58us/step - loss: 0.6113 - accuracy: 0.7950
Epoch 1/1
7200/7200 [==============================] - 0s 59us/step - loss: 0.5613 - accuracy: 0.7961
Epoch 1/1
7200/7200 [==============================] - 0s 63us/step - loss: 0.5694 - accuracy: 0.7943
Epoch 1/1
7200/7200 [==============================] - 0s 66us/step - loss: 0.5627 - accuracy: 0.7949
Epoch 1/1
7200/7200 [==============================] - 1s 77us/step - loss: 0.5570 - accuracy: 0.7933
Epoch 1/1
7200/7200 [==============================] - 0s 67us/step - loss: 0.5527 - accuracy: 0.7936
Epoch 1/1
7200/7200 [==============================] - 1s 75us/step - loss: 0.5547 - accuracy: 0.7965
Epoch 1/1
7200/7200 [==============================] - 1s 80us/step - loss: 0.5748 - accuracy: 0.7960
Epoch 1/1
7200/7200 [==============================] - 1s 75us/step - loss: 0.5507 - accuracy: 0.7956
Epoch 1/1
7200/7200 [==============================] - 1s 119us/step - loss: 0.562

7200/7200 [==============================] - 1s 166us/step - loss: 0.6425 - accuracy: 0.7944
Epoch 1/1
8000/8000 [==============================] - 1s 179us/step - loss: 0.5617 - accuracy: 0.7944


GridSearchCV(cv=10, error_score='raise-deprecating',
       estimator=<keras.wrappers.scikit_learn.KerasClassifier object at 0x000001DE91199048>,
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'batch_size': [25, 32], 'nb_epoch': [100, 500], 'optimizer': ['adam', 'rmsprop']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=0)

In [50]:
best_parameters = grid_search.best_params_
best_parameters

{'batch_size': 25, 'nb_epoch': 100, 'optimizer': 'adam'}

In [51]:
best_accuracy = grid_search.best_score_
best_accuracy

0.796